SRC: [
	"common/gamemain.cpp",
	"common/script.cpp",
	"common/fmfmap.cpp",
	"common/util.cpp",
	"common/map.cpp",
	"common/party.cpp",
	"common/mapscene.cpp",
	"common/battlescene.cpp",
	"common/enemy.cpp",
	"common/database.cpp",
	"main.cpp"
	]
CFLAGS: "cl /c /nologo /MT /EHsc"
CINCLUDES: [".", "common", "dxlib"]
LFLAGS : "/out:main.exe /SUBSYSTEM:WINDOWS /LIBPATH:dxlib"
OBJDIR: "build/"